version: '2'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    volumes:
    - ./app:/usr/src/app/:rw
    environment:
    - NODE_ENV=dev
  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile
    ports:
    - 80:80
    depends_on:
    - web
