version: '2'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    expose:
    - "8080"
    volumes:
    - ./app:/usr/src/app/:rw
    environment:
    - NODE_ENV=dev
  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile
    ports:
    - 80:80
    expose:
    - "80"
    - "8080"
    environment:
    - NGINX_PORT=8080
    - WEPAPP_PORT=8181
